config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users

  resources :reports
  resources :sales do 
    resources :sale_details
  end


  resources :product_lines
  resources :clients
  
  resources :branch_offices do
    resources :areas
    resources :products
    resources :employees  
  end

  resources :managers do
    collection do
      get  :new_manager
      post :create_manager
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  belongs_to :branch_office
  has_many :users
end

app/models/branch_office.rb
class BranchOffice < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many :areas
  has_many :users, :through => :areas
  has_many :products
  has_many :reports
  has_many :sales, :through => :user
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :department
  has_many :branch_offices

  def description
    "#{self.name} #{self.department.name}"
  end
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :sales
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_line
  belongs_to :branch_office
end

app/models/product_line.rb
class ProductLine < ApplicationRecord
  has_many :products
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :branch_office
  belongs_to :user
  has_one :area, :through => :user
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :client
  belongs_to :user
end

app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
  belongs_to :sale
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # belongs_to :branch_office
  belongs_to :area, :class_name => 'Area' unless :new_record?
  has_many :sales
  has_many :reports

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:admin, :user, :seller, :analyst, :coordinator, :manager, :employee]

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def description
    "#{self.names} #{self.last_names} | #{self.identification}"
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :set_areas, onli: [:new, :edit]
  after_action :verify_authorized

  # GET /clients
  # GET /clients.json
  def index
    @users = BranchOffice.find(params[:branch_office_id]).users.employee
    authorize @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
    authorize @user
  end

  def new_manager
    @user = User.new
    authorize @user
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user
  end

  # GET /users/1/edit
  def edit
    authorize @user
  end

  def create_manager
    @user = User.new(employee_params)
    authorize @user

    respond_to do |format|
      if @user.save
        @user.manager!
        format.html { redirect_to branch_office_employees_path, notice: 'user was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(employee_params)
    authorize @user

    respond_to do |format|
      if @user.save
        @user.employee!
        format.html { redirect_to branch_office_employees_path, notice: 'user was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize @user

    respond_to do |format|
      if @user.update(employee_params)
        format.html { redirect_to branch_office_employees_path, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize @user

    @user.destroy
    respond_to do |format|
      format.html { redirect_to branch_office_employees_path, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_areas
    @areas = BranchOffice.includes(:areas).find(params[:branch_office_id]).areas
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:user).permit(:names, :identification, :last_names, :password, :email, :area_id, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true, url: url) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>
  <% unless params[:action].eql?('new_manager')  %>
    <div class="field form-group">
      <%= form.label :area %>
      <%= form.select :area_id, options_from_collection_for_select(@areas, :id, :name, employee.area_id) %>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :names %>
    <%= form.text_field :names, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :last_names %>
    <%= form.text_field :last_names, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :identification %>
    <%= form.text_field :identification, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <% if employee.new_record? %>
  <div class="field form-group">
    <%= form.label :password %>
    <%= form.password_field :password , class: 'form-control'%>
  </div>
  <% end %>


  <div class="actions">
    <%= form.submit 'Guardar', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<%= render 'form', employee: @user, url: branch_office_employee_path(@user, branch_office_id: params[:branch_office_id]) %>

<p>
  <%= link_to 'Ver', branch_office_employee_path(@user, branch_office_id: params[:branch_office_id]) %> |
  <%= link_to 'Regresar', branch_office_path(params[:branch_office_id]) %>
  </p>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "<- Sucursal #{BranchOffice.find(params[:branch_office_id]).name}", branch_office_path(params[:branch_office_id]) %>

<h1>Empleados</h1>

<table id="example" class="table table-striped table-bordered" style="width:100%" >
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Identificación</th>
      <th>Amail</th>
      <th>Area</th>
      <th colspan=""></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |employee| %>
      <tr>
        <td><%= employee.names %></td>
        <td><%= employee.identification %></td>
        <td><%= employee.email %></td>
        <td><%= employee.area.name %></td>
        <td><%= link_to 'Ver', branch_office_employees_path(employee, branch_office_id: params[:branch_office_id]) %>
        <%= link_to 'Editar', edit_branch_office_employee_path(employee, branch_office_id: params[:branch_office_id] ) %>
        <%= link_to 'Eliminar', branch_office_employees_path(employee, branch_office_id: params[:branch_office_id]), method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Registrar Empleado', new_branch_office_employee_path %>

app/views/employees/new.html.erb
<%= render 'form', employee: @user, url: branch_office_employees_path %>