config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users

  resources :reports
  resources :sales do 
    resources :sale_details
  end


  resources :product_lines
  resources :clients
  
  resources :branch_offices do
    resources :areas
    resources :products
    resources :employees  
  end

  resources :managers do
    collection do
      get  :new_manager
      post :create_manager
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  belongs_to :branch_office
  has_many :users
end

app/models/branch_office.rb
class BranchOffice < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many :areas
  has_many :users, :through => :areas
  has_many :products
  has_many :reports
  has_many :sales, :through => :user
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :department
  has_many :branch_offices

  def description
    "#{self.name} #{self.department.name}"
  end
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :sales
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_line
  belongs_to :branch_office
end

app/models/product_line.rb
class ProductLine < ApplicationRecord
  has_many :products
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :branch_office
  belongs_to :user
  has_one :area, :through => :user
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :client
  belongs_to :user
end

app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
  belongs_to :sale
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # belongs_to :branch_office
  belongs_to :area, :class_name => 'Area' unless :new_record?
  has_many :sales
  has_many :reports

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:admin, :user, :seller, :analyst, :coordinator, :manager, :employee]

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def description
    "#{self.names} #{self.last_names} | #{self.identification}"
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.where(branch_office_id: params[:branch_office_id])
    authorize @areas
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    authorize @area
  end

  # GET /areas/new
  def new
    @area = Area.new
    authorize @area
  end

  # GET /areas/1/edit
  def edit
    authorize @area
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)
    authorize @area

    respond_to do |format|
      if @area.save
        format.html { redirect_to branch_office_areas_path, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    authorize @area

    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to branch_office_areas_path, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    authorize @area

    @area.destroy
    respond_to do |format|
      format.html { redirect_to branch_office_areas_path, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :branch_office_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:home]

  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sale_details_helper.rb
module SaleDetailsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true, url: url ) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :branch_office_id, value:params[:branch_office_id] %>
  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area, url: branch_office_area_path( @area, branch_office_id: params[:branch_office_id])  %>

<%= link_to 'Show', branch_office_area_path(@area, branch_office_id: params[:branch_office_id]) %> |
<%= link_to 'Back', branch_office_areas_path(branch_office_id: params[:branch_office_id] ) %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "<- Sucursal #{BranchOffice.find(params[:branch_office_id]).name}", branch_office_path(params[:branch_office_id]) %>
<h1>Areas</h1>

<table id="example" class="table table-striped table-bordered" style="width:100%" >
  <thead>
    <tr>
      <th>Name</th>
      <th>Fecha Creación</th>
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= area.created_at %></td>
        <td><%= link_to 'Ver', branch_office_area_path(area, branch_office_id: params[:branch_office_id]) %>
        <%= link_to 'Editar', edit_branch_office_area_path(area, branch_office_id: params[:branch_office_id]) %>
        <%= link_to 'Eliminar', branch_office_area_path(area, branch_office_id: params[:branch_office_id]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear Area', new_branch_office_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area, url: branch_office_areas_path %>

<%= link_to 'Back', branch_office_areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @area.name %>
</p>

<p>
  <strong>Branch office:</strong>
  <%= @area.branch_office %>
</p>

<%= link_to 'Edit', edit_branch_office_area_path(@area, branch_office_id: params[:branch_office_id] ) %> |
<%= link_to 'Back', branch_office_areas_path(params[:branch_office_id]) %>