config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users

  resources :reports
  resources :sales do 
    resources :sale_details
  end


  resources :product_lines
  resources :clients
  
  resources :branch_offices do
    resources :areas
    resources :products
    resources :employees  
  end

  resources :managers do
    collection do
      get  :new_manager
      post :create_manager
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  belongs_to :branch_office
  has_many :users
end

app/models/branch_office.rb
class BranchOffice < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many :areas
  has_many :users, :through => :areas
  has_many :products
  has_many :reports
  has_many :sales, :through => :user
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :department
  has_many :branch_offices

  def description
    "#{self.name} #{self.department.name}"
  end
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :sales
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_line
  belongs_to :branch_office
end

app/models/product_line.rb
class ProductLine < ApplicationRecord
  has_many :products
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :branch_office
  belongs_to :user
  has_one :area, :through => :user
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :client
  belongs_to :user
end

app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
  belongs_to :sale
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # belongs_to :branch_office
  belongs_to :area, :class_name => 'Area' unless :new_record?
  has_many :sales
  has_many :reports

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:admin, :user, :seller, :analyst, :coordinator, :manager, :employee]

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def description
    "#{self.names} #{self.last_names} | #{self.identification}"
  end
end

app/controllers/branch_offices_controller.rb
class BranchOfficesController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  before_action :set_branch_office, only: [:show, :edit, :update, :destroy]
  before_action :set_collections, only: [:new, :edit]

  # GET /branch_offices
  # GET /branch_offices.json
  def index
    @branch_offices = BranchOffice.all
    authorize @branch_offices
  end

  # GET /branch_offices/1
  # GET /branch_offices/1.json
  def show
    authorize @branch_office
  end

  # GET /branch_offices/new
  def new
    @branch_office = BranchOffice.new
    authorize @branch_office
  end

  # GET /branch_offices/1/edit
  def edit
    authorize @branch_office
  end

  # POST /branch_offices
  # POST /branch_offices.json
  def create
    @branch_office = BranchOffice.new(branch_office_params)
    authorize @branch_office

    respond_to do |format|
      if @branch_office.save
        format.html { redirect_to @branch_office, notice: 'Branch office was successfully created.' }
        format.json { render :show, status: :created, location: @branch_office }
      else
        format.html { render :new }
        format.json { render json: @branch_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branch_offices/1
  # PATCH/PUT /branch_offices/1.json
  def update
    @branch_office
    authorize @branch_office

    respond_to do |format|
      if @branch_office.update
        format.html { redirect_to @branch_office, notice: 'Branch office was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch_office }
      else
        format.html { render :edit }
        format.json { render json: @branch_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branch_offices/1
  # DELETE /branch_offices/1.json
  def destroy
    authorize @branch_office
    @branch_office.destroy
    respond_to do |format|
      format.html { redirect_to branch_offices_url, notice: 'Branch office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_collections
    @users = User.manager
    @cities = City.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch_office
      @branch_office = BranchOffice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_office_params
      params.require(:branch_office).permit(:city_id, :user_id, :name, :telephone, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/branch_offices_helper.rb
module BranchOfficesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sale_details_helper.rb
module SaleDetailsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/branch_offices/_form.html.erb
<%= form_with(model: branch_office, local: true) do |form| %>
  <% if branch_office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(branch_office.errors.count, "error") %> prohibited this branch_office from being saved:</h2>

      <ul>
      <% branch_office.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :city_id %>
    <%= form.select :city_id, options_from_collection_for_select(@cities, :id, :description ),{}, {
      class: 'form-control'} %>
  </div>

  <div class="field form-group">
    <%= form.label :Gerente %>
    <%= form.select :user_id, options_from_collection_for_select(@users, :id, :description),{}, {
      class: 'form-control'} %>
  </div>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :telephone, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: "btn btn-primary"%>
  </div>
<% end %>

app/views/branch_offices/edit.html.erb
<h1>Editing Branch Office</h1>

<%= render 'form', branch_office: @branch_office %>

<%= link_to 'Show', @branch_office %> |
<%= link_to 'Back', branch_offices_path %>

app/views/branch_offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sucursales</h1>

<table id="example" class="table table-striped table-bordered" style="width:100%" >
  <thead>
    <tr>
      <th>Ciudad</th>
      <th>Gerente</th>
      <th>Nombre</th>
      <th>Teléfono</th>
      <th>Dirección</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @branch_offices.each do |branch_office| %>
      <tr>
        <td><%= branch_office.city.description %></td>
        <td><%= branch_office.user.description %></td>
        <td><%= branch_office.name %></td>
        <td><%= branch_office.telephone %></td>
        <td><%= branch_office.address %></td>
        <td><%= link_to 'Ver', branch_office %>
        <%= link_to 'Editar', edit_branch_office_path(branch_office) %>
        <%= link_to 'Eliminar', branch_office, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Sucursal', new_branch_office_path %>

app/views/branch_offices/new.html.erb
<h1>New Branch Office</h1>

<%= render 'form', branch_office: @branch_office %>

<%= link_to 'Back', branch_offices_path, class: "btn btn-black" %>

app/views/branch_offices/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= link_to 'Empleados', branch_office_employees_path(@branch_office) %> |
  <%= link_to 'Areas', branch_office_areas_path(@branch_office) %> |
  <%= link_to 'Productos', branch_office_products_path(@branch_office) %>
</p>
<p>
  <strong>City:</strong>
  <%= @branch_office.city.description %>
</p>

<p>
  <strong>Gerente:</strong>
  <%= @branch_office.user.description %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @branch_office.name %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @branch_office.telephone %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @branch_office.address %>
</p>

  <%= link_to 'Editar', edit_branch_office_path(@branch_office) %> |
  <%= link_to 'Regresar', branch_offices_path %>